server:
  port: 9001

spring:
  application:
    name: tensquare-baser #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.147.128:3306/tensquare_base
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true